<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="FluentIcons.Avalonia.Fluent"/>
        <PackageReference Include="FluentIcons.Common"/>
        <PackageReference Include="Humanizer.Core"/>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\Window\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Controls\HomeView.axaml.cs">
            <DependentUpon>HomeView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Controls\MainView.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Controls\SettingsView.axaml.cs">
            <DependentUpon>SettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\DialogControls\MessageDialogControl.axaml.cs">
            <DependentUpon>MessageDialogControl.axaml.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\PageControls\QueuePageView.axaml.cs">
            <DependentUpon>QueuePageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>
</Project>
